import { PrismaClient } from '@prisma/client';

export async function seedModules(prisma: PrismaClient) {
  console.log('📦 Seeding modules...');

  const modules = [
    // Admin Modules (2)
    {
      name: 'god-mode',
      displayName: 'God Mode',
      description: 'System-wide administration and God Mode features',
      icon: 'Shield',
      path: '/dashboard/god-mode',
      category: 'Admin',
      enabled: true,
      settings: {
        allowSystemConfig: true,
        allowUserManagement: true,
        allowLicenseManagement: true,
        allowBackupManagement: true,
      },
      dependencies: [],
      features: ['System config', 'User management', 'License management', 'Backup management'],
    },
    {
      name: 'super-admin',
      displayName: 'Super Admin',
      description: 'Super administrator panel',
      icon: 'Shield',
      path: '/dashboard/super-admin',
      category: 'Admin',
      enabled: true,
      settings: {
        allowFullAccess: true,
        allowAdminControls: true,
      },
      dependencies: [],
      features: ['Full system access', 'Admin controls'],
    },

    // Member & Organization Management (8)
    {
      name: 'members',
      displayName: 'Members Management',
      description: 'Comprehensive member management',
      icon: 'Users',
      path: '/dashboard/members',
      category: 'Core',
      enabled: true,
      settings: {
        allowImport: true,
        allowExport: true,
        requireApproval: false,
      },
      dependencies: [],
      features: ['Add/Edit/Delete', 'Import/Export', 'Member profiles', 'Categorization'],
    },
    {
      name: 'member',
      displayName: 'Member Profile',
      description: 'Individual member profiles',
      icon: 'Users',
      path: '/dashboard/member',
      category: 'Core',
      enabled: true,
      settings: {
        allowViewProfile: true,
        allowEditDetails: true,
      },
      dependencies: ['members'],
      features: ['View profile', 'Edit details', 'History'],
    },
    {
      name: 'families',
      displayName: 'Families',
      description: 'Family relationship management',
      icon: 'Users',
      path: '/dashboard/families',
      category: 'Core',
      enabled: true,
      settings: {
        allowFamilyTrees: true,
        allowRelationships: true,
      },
      dependencies: ['members'],
      features: ['Family trees', 'Relationships', 'Grouping'],
    },
    {
      name: 'groups',
      displayName: 'Groups',
      description: 'Group and team management',
      icon: 'Users',
      path: '/dashboard/groups',
      category: 'Core',
      enabled: true,
      settings: {
        allowCreateGroups: true,
        allowManageMembers: true,
      },
      dependencies: ['members'],
      features: ['Create groups', 'Manage members', 'Group roles'],
    },
    {
      name: 'volunteers',
      displayName: 'Volunteers',
      description: 'Volunteer management',
      icon: 'Users',
      path: '/dashboard/volunteers',
      category: 'Core',
      enabled: true,
      settings: {
        allowRegistry: true,
        allowScheduling: true,
      },
      dependencies: ['members'],
      features: ['Volunteer registry', 'Scheduling', 'Hours tracking'],
    },
    {
      name: 'children',
      displayName: 'Children',
      description: 'Children and youth management',
      icon: 'Users',
      path: '/dashboard/children',
      category: 'Core',
      enabled: true,
      settings: {
        allowYouthRegistry: true,
        allowPrograms: true,
      },
      dependencies: ['members'],
      features: ['Youth registry', 'Programs', 'Activities'],
    },
    {
      name: 'user-management',
      displayName: 'User Management',
      description: 'User account management',
      icon: 'Users',
      path: '/dashboard/user-management',
      category: 'Core',
      enabled: true,
      settings: {
        allowUserAccounts: true,
        allowRoles: true,
        allowPermissions: true,
      },
      dependencies: [],
      features: ['User accounts', 'Roles', 'Permissions'],
    },

    // Financial Management (3)
    {
      name: 'finances',
      displayName: 'Finances',
      description: 'Main financial management system',
      icon: 'DollarSign',
      path: '/dashboard/finances',
      category: 'Core',
      enabled: true,
      settings: {
        allowDonations: true,
        allowExpenses: true,
        allowReconciliation: true,
      },
      dependencies: ['members'],
      features: ['Donations', 'Expenses', 'Reports', 'Reconciliation'],
    },
    {
      name: 'branch-finances',
      displayName: 'Branch Finances',
      description: 'Branch-level financial management',
      icon: 'DollarSign',
      path: '/dashboard/branch-finances',
      category: 'Core',
      enabled: true,
      settings: {
        allowBranchBudgets: true,
        allowLocalReports: true,
      },
      dependencies: ['finances'],
      features: ['Branch budgets', 'Local reports'],
    },
    {
      name: 'subscription-manager',
      displayName: 'Subscriptions',
      description: 'Subscription and billing management',
      icon: 'DollarSign',
      path: '/dashboard/subscription-manager',
      category: 'Core',
      enabled: true,
      settings: {
        allowPlans: true,
        allowBilling: true,
        allowPayments: true,
      },
      dependencies: ['members'],
      features: ['Plans', 'Billing', 'Payments', 'Analytics'],
    },

    // Events & Activities (5)
    {
      name: 'events',
      displayName: 'Events',
      description: 'Event management',
      icon: 'Calendar',
      path: '/dashboard/events',
      category: 'Core',
      enabled: true,
      settings: {
        allowCreateEvents: true,
        allowRegistration: true,
      },
      dependencies: ['members'],
      features: ['Create events', 'Registration', 'Attendance'],
    },
    {
      name: 'calendar',
      displayName: 'Calendar',
      description: 'Calendar and scheduling',
      icon: 'Calendar',
      path: '/dashboard/calendar',
      category: 'Core',
      enabled: true,
      settings: {
        allowScheduling: true,
        allowReminders: true,
      },
      dependencies: [],
      features: ['Schedule events', 'View calendar', 'Reminders'],
    },
    {
      name: 'attendance',
      displayName: 'Attendance',
      description: 'Attendance tracking system',
      icon: 'CheckCircle',
      path: '/dashboard/attendance',
      category: 'Core',
      enabled: true,
      settings: {
        allowCheckIn: true,
        allowReports: true,
      },
      dependencies: ['members'],
      features: ['Check-in', 'Reports', 'Analytics'],
    },
    {
      name: 'pastoral-care',
      displayName: 'Pastoral Care',
      description: 'Pastoral care management',
      icon: 'Heart',
      path: '/dashboard/pastoral-care',
      category: 'Core',
      enabled: true,
      settings: {
        allowCareTracking: true,
        allowFollowUps: true,
      },
      dependencies: ['members'],
      features: ['Care tracking', 'Follow-ups', 'Notes'],
    },
    {
      name: 'prayer-requests',
      displayName: 'Prayer Requests',
      description: 'Prayer request management',
      icon: 'Heart',
      path: '/dashboard/prayer-requests',
      category: 'Core',
      enabled: true,
      settings: {
        allowSubmitRequests: true,
        allowTrackPrayers: true,
      },
      dependencies: ['members'],
      features: ['Submit requests', 'Track prayers'],
    },

    // Communication & Broadcasting (4)
    {
      name: 'communication',
      displayName: 'Communication',
      description: 'Multi-channel messaging',
      icon: 'MessageSquare',
      path: '/dashboard/communication',
      category: 'Core',
      enabled: true,
      settings: {
        allowEmail: true,
        allowSMS: false,
        allowPushNotifications: true,
      },
      dependencies: ['members'],
      features: ['Email', 'SMS', 'Push notifications', 'Broadcast'],
    },
    {
      name: 'broadcasts',
      displayName: 'Broadcasts',
      description: 'Broadcasting system',
      icon: 'MessageSquare',
      path: '/dashboard/broadcasts',
      category: 'Core',
      enabled: true,
      settings: {
        allowMassMessages: true,
        allowScheduling: true,
      },
      dependencies: ['communication'],
      features: ['Mass messages', 'Scheduling'],
    },
    {
      name: 'notifications',
      displayName: 'Notifications',
      description: 'Notification management',
      icon: 'MessageSquare',
      path: '/dashboard/notifications',
      category: 'Core',
      enabled: true,
      settings: {
        allowPushAlerts: true,
        allowPreferences: true,
      },
      dependencies: [],
      features: ['Push alerts', 'Preferences'],
    },
    {
      name: 'sermons',
      displayName: 'Sermons',
      description: 'Sermon management',
      icon: 'MessageSquare',
      path: '/dashboard/sermons',
      category: 'Core',
      enabled: true,
      settings: {
        allowUpload: true,
        maxFileSize: 500,
      },
      dependencies: [],
      features: ['Upload sermons', 'Archive', 'Share'],
    },

    // Sacraments & Registries (3)
    {
      name: 'sacraments',
      displayName: 'Sacraments',
      description: 'Sacrament management',
      icon: 'CheckCircle',
      path: '/dashboard/sacraments',
      category: 'Core',
      enabled: true,
      settings: {
        allowRecordSacraments: true,
        allowCertificates: true,
      },
      dependencies: ['members'],
      features: ['Record sacraments', 'Certificates', 'History'],
    },
    {
      name: 'birth-registry',
      displayName: 'Birth Registry',
      description: 'Birth registration management',
      icon: 'CheckCircle',
      path: '/dashboard/birth-registry',
      category: 'Core',
      enabled: true,
      settings: {
        allowBirthRecords: true,
        allowStatistics: true,
      },
      dependencies: [],
      features: ['Birth records', 'Certificates', 'Statistics'],
    },
    {
      name: 'death-register',
      displayName: 'Death Register',
      description: 'Death registration',
      icon: 'CheckCircle',
      path: '/dashboard/death-register',
      category: 'Core',
      enabled: true,
      settings: {
        allowDeathRecords: true,
        allowCertificates: true,
      },
      dependencies: [],
      features: ['Death records', 'Certificates'],
    },

    // Organization & Administration (6)
    {
      name: 'admin',
      displayName: 'Admin',
      description: 'System administration',
      icon: 'Settings',
      path: '/dashboard/admin',
      category: 'Core',
      enabled: true,
      settings: {
        allowSystemConfig: true,
        allowUserRoles: true,
        allowPermissions: true,
      },
      dependencies: [],
      features: ['System config', 'User roles', 'Permissions'],
    },
    {
      name: 'branches',
      displayName: 'Branches',
      description: 'Multi-branch management',
      icon: 'Shield',
      path: '/dashboard/branches',
      category: 'Core',
      enabled: true,
      settings: {
        allowBranchSetup: true,
        allowHierarchy: true,
      },
      dependencies: [],
      features: ['Branch setup', 'Hierarchy', 'Operations'],
    },
    {
      name: 'branch',
      displayName: 'Branch',
      description: 'Branch operations',
      icon: 'Shield',
      path: '/dashboard/branch',
      category: 'Core',
      enabled: true,
      settings: {
        allowBranchSettings: true,
        allowOperations: true,
      },
      dependencies: ['branches'],
      features: ['Branch settings', 'Operations'],
    },
    {
      name: 'branch-admin',
      displayName: 'Branch Admin',
      description: 'Branch administration',
      icon: 'Shield',
      path: '/dashboard/branch-admin',
      category: 'Core',
      enabled: true,
      settings: {
        allowBranchControl: true,
      },
      dependencies: ['branches'],
      features: ['Branch control'],
    },
    {
      name: 'zones',
      displayName: 'Zones',
      description: 'Zone management',
      icon: 'MapPin',
      path: '/dashboard/zones',
      category: 'Core',
      enabled: true,
      settings: {
        allowCreateZones: true,
        allowManageAreas: true,
      },
      dependencies: [],
      features: ['Create zones', 'Manage areas'],
    },
    {
      name: 'ministries',
      displayName: 'Ministries',
      description: 'Ministry management',
      icon: 'Sparkles',
      path: '/dashboard/ministries',
      category: 'Core',
      enabled: true,
      settings: {
        allowMinistrySetup: true,
        allowTeams: true,
      },
      dependencies: [],
      features: ['Ministry setup', 'Teams', 'Activities'],
    },

    // Data & Reporting (4)
    {
      name: 'analytics',
      displayName: 'Analytics',
      description: 'Analytics and dashboards',
      icon: 'BarChart3',
      path: '/dashboard/analytics',
      category: 'Core',
      enabled: true,
      settings: {
        allowDashboards: true,
        allowCharts: true,
      },
      dependencies: [],
      features: ['Dashboards', 'Charts', 'Insights'],
    },
    {
      name: 'reports',
      displayName: 'Reports',
      description: 'Report generation',
      icon: 'BarChart3',
      path: '/dashboard/reports',
      category: 'Core',
      enabled: true,
      settings: {
        allowGenerateReports: true,
        allowExportData: true,
      },
      dependencies: [],
      features: ['Generate reports', 'Export data'],
    },
    {
      name: 'report-builder',
      displayName: 'Report Builder',
      description: 'Custom report builder',
      icon: 'BarChart3',
      path: '/dashboard/report-builder',
      category: 'Core',
      enabled: true,
      settings: {
        allowCustomReports: true,
        allowTemplates: true,
        allowScheduling: true,
      },
      dependencies: [],
      features: ['Custom reports', 'Templates', 'Scheduling'],
    },
    {
      name: 'audits',
      displayName: 'Audits',
      description: 'Audit logging and compliance',
      icon: 'Lock',
      path: '/dashboard/audits',
      category: 'Core',
      enabled: true,
      settings: {
        allowAuditTrails: true,
        allowCompliance: true,
      },
      dependencies: [],
      features: ['Audit trails', 'Compliance'],
    },

    // Content & Integration (4)
    {
      name: 'cms',
      displayName: 'CMS',
      description: 'Content management system',
      icon: 'Edit2',
      path: '/dashboard/cms',
      category: 'Core',
      enabled: true,
      settings: {
        allowContentPages: true,
        allowMedia: true,
        allowPublishing: true,
      },
      dependencies: [],
      features: ['Content pages', 'Media', 'Publishing'],
    },
    {
      name: 'website-integration',
      displayName: 'Website Integration',
      description: 'Website integration',
      icon: 'Edit2',
      path: '/dashboard/website-integration',
      category: 'Core',
      enabled: true,
      settings: {
        allowWebsiteSync: true,
        allowAPIIntegration: true,
      },
      dependencies: [],
      features: ['Website sync', 'API integration'],
    },
    {
      name: 'mobile-integration',
      displayName: 'Mobile Integration',
      description: 'Mobile app integration',
      icon: 'Edit2',
      path: '/dashboard/mobile-integration',
      category: 'Core',
      enabled: true,
      settings: {
        allowMobileSync: true,
        allowPushNotifications: true,
      },
      dependencies: [],
      features: ['Mobile sync', 'Push notifications'],
    },
    {
      name: 'workflows',
      displayName: 'Workflows',
      description: 'Workflow automation',
      icon: 'Zap',
      path: '/dashboard/workflows',
      category: 'Core',
      enabled: true,
      settings: {
        allowAutomation: true,
        allowTriggers: true,
        allowActions: true,
      },
      dependencies: [],
      features: ['Automation', 'Triggers', 'Actions'],
    },

    // Assets & Settings (3)
    {
      name: 'assets',
      displayName: 'Assets',
      description: 'Asset management and tracking',
      icon: 'HardDrive',
      path: '/dashboard/assets',
      category: 'Core',
      enabled: true,
      settings: {
        allowAssetRegistry: true,
        allowTracking: true,
        allowDepreciation: true,
      },
      dependencies: [],
      features: ['Asset registry', 'Tracking', 'Depreciation'],
    },
    {
      name: 'settings',
      displayName: 'Settings',
      description: 'System settings',
      icon: 'Settings',
      path: '/dashboard/settings',
      category: 'Core',
      enabled: true,
      settings: {
        allowConfiguration: true,
        allowPreferences: true,
      },
      dependencies: [],
      features: ['Configuration', 'Preferences', 'Defaults'],
    },
    {
      name: 'profile',
      displayName: 'Profile',
      description: 'User profile management',
      icon: 'Users',
      path: '/dashboard/profile',
      category: 'Core',
      enabled: true,
      settings: {
        allowUserProfiles: true,
        allowPreferences: true,
      },
      dependencies: [],
      features: ['User profiles', 'Settings', 'Preferences'],
    },

    // Shared Components (1)
    {
      name: 'components',
      displayName: 'Components',
      description: 'Reusable UI components library',
      icon: 'Sparkles',
      path: '/dashboard/components',
      category: 'Shared',
      enabled: true,
      settings: {
        allowUIComponents: true,
        allowDesignSystem: true,
      },
      dependencies: [],
      features: ['UI components', 'Design system'],
    },

    // Worship (1)
    {
      name: 'worship',
      displayName: 'Worship',
      description: 'Worship management',
      icon: 'Heart',
      path: '/dashboard/worship',
      category: 'Core',
      enabled: true,
      settings: {
        allowWorshipPlanning: true,
        allowTeams: true,
        allowResources: true,
      },
      dependencies: [],
      features: ['Worship planning', 'Teams', 'Resources'],
    },
  ];

  let createdCount = 0;
  let updatedCount = 0;

  for (const module of modules) {
    const existing = await prisma.module.findUnique({
      where: { name: module.name },
    });

    if (existing) {
      // Update existing
      await prisma.module.update({
        where: { name: module.name },
        data: module,
      });
      updatedCount++;
    } else {
      // Create new
      await prisma.module.create({
        data: module,
      });
      createdCount++;
    }
  }

  console.log(`✅ Modules seeded: ${createdCount} created, ${updatedCount} updated (Total: ${modules.length})`);
}
